config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/dionysus', as: 'rails_admin'
  devise_for :users
  root to: 'events#home'

  get "/loading", to: 'events#loading'

  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"

  require "sidekiq/web"

  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_cards.html.erb
<div class="col-xs-12 col-md-6">
  <div class="result-card">
    <div class="result-card-image">
      <% photo = event.photos? ? cl_image_path(event.photos, height: 300, width: 400, crop: :fill) : 'http://diocesisdecucuta.com/diocesis2/wp-content/uploads/2017/08/n2-3.png'%>
      <img class="card-img" src=('<%= photo %>') alt="">
    </div>
    <div class="result-card-details">
      <div class="result-card-details-left">
        <h4><%= event.city_airport.city_name %></h4>
        <p><%= event.title %></p>
      </div>
      <div class="result-card-details-right">
        <p>Flight + Hotel</p>
        <% hotel_price = @result_hash[event.city_airport.city_name][:hotel_api_info]['minRate'] %>
        <% flight_price_string = @result_hash[event.city_airport.city_name][:flight_api_info]['trips']['tripOption'][0]['pricing'][0]['saleTotal'] %>
        <% price_flight = flight_price_string.slice! "EUR" %>
        <h4>€ <%= price_flight.to_f + hotel_price.to_f %></h4>
      </div>
    </div>
    <div class="result-hover-card">
      <div class="result-hover-card-details">
        <div class="result-card-details-left">
          <h4><%= event.city_airport.city_name %></h4>
          <p><%= event.title %></p>
        </div>
        <div class="result-card-details-right">
          <p>Flight + Hotel</p>
          <h4>€150</h4>
        </div>
      </div>
      <div>
        <p class="result-hover-description">The biggest street festival in Barcelona is the Gracia festival every year in mid August called the Festa Major de Gracia and also often called the Fiesta de Gracia.  Around 17 streets are decorate by the residents. There are hundreds of activities most of which are for local residents, but tourists and visitors are welcome to the concerts and parades. <!-- The Festa de Gracia is about Catalan traditions like parades, giants, castle building and fireruns, but most of all it is a shining... --></p>
      </div>
      <div>
        <a href="events/<%= Event.first.id %>" class="btn btn-lg book-button">BOOK</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <h5>Know a great event that isn't on Daylily?</h5>
    <%= link_to "Please let us know!", new_event_path, class: "btn btn-sm new-event-button"%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>